### PR TITLE
Create .krew.yaml

### PR DESCRIPTION
**Pull request by rajatjindal**
fixes https://github.com/robscott/kube-capacity/issues/20

Once this PR is merged, please configure the webhook using instructions here: https://github.com/rajatjindal/krew-release-bot#how-to-install

Look forward for seeing this in action for your repo. happy to help, if you runs into any issue with this.

Thanks
Rajat Jindal

### CODE REVIEW

**Comment by rajatjindal** [comment]
I ran it locally using latest release, and got this yaml file:

```yaml
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: resource-capacity
spec:
  version: v0.3.3
  homepage: https://github.com/robscott/kube-capacity
  shortDescription: Provides an overview of resource requests, limits, and utilization
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    bin: kube-capacity
    files:
    - from: "*"
      to: "."
    uri: https://github.com/robscott/kube-capacity/releases/download/0.3.3/kube-capacity_0.3.3_Darwin_x86_64.tar.gz
    sha256: 539747ab82ebfec72c3340c40661fdfd62108a5d305dbf5a7e43f9ca6428748b    
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    bin: kube-capacity
    files:
    - from: "*"
      to: "."
    uri: https://github.com/robscott/kube-capacity/releases/download/0.3.3/kube-capacity_0.3.3_Linux_x86_64.tar.gz
    sha256: 7869bfe301e471a9e1cf539b4a9062b672cc5d71a08da510ed6ca7aaaf7c7c46
  description: |
    A simple CLI that provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster.

```

**Comment by rajatjindal** [comment]
This is obsolete after we did iterations of recommendations from krew team. I will open a new PR soon for you. Thanks

**Comment by robscott** [comment]
Hey @rajatjindal, thanks for your work on this! Let me know if you're able to get the new approach working.

**Comment by rajatjindal** [comment]
yes, we got that working. I will try to find time this week to submit new PR for this.

**Comment by rajatjindal** [comment]
Hi Rob,

I looked at the repo, and couldn't make out how the release are being created. I am guessing you are running go-releaser manually to create the release? and also packaging this for brew.

If my understanding is right, let me know how would you like to prefer this setup. there are a few options I can think of:

- update circle-ci to call go-releaser and create the release. We will also update circle-ci to run krew-release-bot after that.
- move the CI to use github actions (we have tested this with other plugins)

if my understanding is wrong, could you please help me understand how the releases are done, and I will think of how krew-release-bot will integrate with that process.

Many thanks
Rajat Jindal

**Comment by robscott** [comment]
Hey @rajatjindal, thanks for your help with this! You're right, all releases have been done manually at this point, just by running goreleaser. Very open to other approaches, either CircleCI or GitHub actions.

**Comment by rajatjindal** [comment]
closing in favor of #26

**Pull request closed without merging**
