### PR TITLE
Added kube-capacity to AUR for ArchLinux

### PR DESCRIPTION
**Pull request by Toxblh**

### CODE REVIEW

**Comment by robscott** [comment]
This is really cool, thanks! How is this registry updated? Will I need to publish new versions to this registry? How can I be sure that what's published there is actually kube-capacity?

**Comment by Toxblh** [comment]
1. At current moment manually update only.
2. Yes need to publish new, every time need to update sha256 sum as well for the binary
3. You can open https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kube-capacity 
`source=("https://github.com/robscott/kube-capacity/releases/download/$pkgver/kube-capacity_"$pkgver"_Linux_x86_64.tar.gz")`

That what I use for download the package and 
`sha256sums=('5784b819447d823d29622084d86d2e5eca51f7c1c016db0ae17457a7d24c6cd1') `
From your provided check sums.
I install just the binary `install -Dm 755 "$srcdir/kube-capacity" "$pkgdir/usr/bin/kube-capacity"`

As I know, some guys provides PKGBUILD from the repo. Like example, just create a folder and upd PKGBUILD manually in repo or automatic for each release. Need to investigate that moment. Or just to provide access to update to you, as I know it's possible to do.. This registry like [git repo](https://aur.archlinux.org/kube-capacity.git/) with [2 files ](https://aur.archlinux.org/cgit/aur.git/tree/?h=kube-capacity)

That just my first AUR package, and that is works.

**Comment by Toxblh** [comment]
I researched a bit. 
This is repo only with access for me. If you create an account, I can provide to you the repo.
Logic how it's work very similar to brew, but with self git server for that. Just need to commit a new version in PKGBUILD.

Anyway, I can maintain the package self.

**Comment by Toxblh** [comment]
I found the guy with circleCI and deploy to AUR. 
https://github.com/tejohnso/dictionary-filter/blob/f62a449436052e4191daf3b2f6bb6c222807dbd0/.circleci/config.yml#L76

**Pull request closed without merging**
