### PR TITLE
changes to do automated releases

### PR DESCRIPTION
**Pull request by rajatjindal**
Hi Rob,

This PR is still work in progress, but enough to get the review started. 

It has following changes:

- updated the version of go to 1.13
- added go-releaser as part of circle-ci config
- fixed the deprecated/removed go-releaser config files
- added krew-release-bot to circle-ci config

TODO:

- release new version of krew-release-bot with circle-ci support (pending review)
- update this PR with new version of krew-release-bot

I am going to close the other 2 PR in favor of this one.

Thanks
Rajat Jindal

### CODE REVIEW

**Comment by rajatjindal** [comment]
Hi @robscott 

Thanks for letting me put up this PR. While doing this PR, I've added support for circle-ci and travis-ci to `krew-release-bot` and released new version for the same.

This PR is now ready for review.

can't wait to see this getting merged.

Thanks
Rajat Jindal

**Comment by robscott** [comment]
Hey @rajatjindal, this is awesome, thanks! What kind of env vars/config would I need to add to CircleCI for this to work?

**Comment by rajatjindal** [comment]
I dont think you need any new env vars or config. It should just work. I will be more than happy to debug if we run into issues (i did tested it while opening the PR)

**Comment by robscott** [comment]
Sounds great, thanks so much for all your work on this!

**Pull request merged**
