### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by day1118**
This PR adds a dockerfile which builds kube-capacity to make it more portable.
It would be great to add an automated build step and push it to a docker registry.

### CODE REVIEW

**Comment by robscott** [comment]
Hey @day1118, thanks for the PR! Is there any particular use case you had in mind for this? I've generally intended for kube-capacity to be a standalone cli tool. I'm not sure how helpful a Docker image would be for this.

**Comment by day1118** [comment]
> Hey @day1118, thanks for the PR! Is there any particular use case you had in mind for this? I've generally intended for kube-capacity to be a standalone cli tool. I'm not sure how helpful a Docker image would be for this.

Hi @robscott 
I have shifted to using almost all cli tools from within docker. Some examples include `gcloud`, `helm`, `kubectl`, `jq`, `kube-linter`, `kubescore` etc. If you create a simple docker compose file, you only need to prepend `docker-compose run` to a command and it will run within a container. I find this great as my team do no need to install any tools, and you can change version back and forth very easily. (eg `docker-compose run kube-capacity --pods --util`)

I'd love this option for `kube-capacity` also, and hope that you will consider automating the container build and pushing it to dockerhub! I'd be happy to help you set this up if you'd like.

**Comment by day1118** [comment]
Hi @robscott 
Any thoughts on merging this?
Thanks

**Comment by robscott** [comment]
Hey @day1118, thanks for the reminder! Unfortunately I don't have the time to set up (and more importantly maintain) a Docker registry for this image. I am open to including a Dockerfile in the repo though. To minimize maintenance and potential vulnerabilities, I'd prefer an image with a [distroless base](https://github.com/GoogleContainerTools/distroless#examples-with-docker) though.

**Comment by day1118** [comment]
That makes sense - I do find that distroless can be quite frustrating to troubleshoot etc as you don't have a shell, but it is your project after all.

**Comment by robscott** [comment]
Yeah I completely get that, I've just been on the hook for keeping images patched that we're not distroless and it was quite a task to keep up with. Unfortunately I just don't think I'd have enough time to keep up with that on this project.

**Comment by robscott** [comment]
Going to close this out since I just haven't had much time to spend on this project. Thanks for the idea though!

**Pull request closed without merging**
